Suspect.destroy_all 

Suspect.create(name: "Charlie Payne", age: 27, gender: "F", location: "London", hair_color: "blonde", one_thing_about: "Huge Apple fan.", into_tech: true, drinks_alcohol: true, multilingual: false)
Suspect.create(name: "Chuk Orakwusi", age: 29, gender: "M", location: "London", hair_color: "black", one_thing_about: "Doesn't like games.", into_tech: true, drinks_alcohol: true, multilingual: true)
Suspect.create(name: "Dorothy John", age: 29, gender: "F", location: "London", hair_color: "blonde", one_thing_about: "Loves to run.", into_tech: true, drinks_alcohol: true, multilingual: true)
Suspect.create(name: "Elena Dinca", age: 35, gender: "F", location: "London", hair_color: "red", one_thing_about: "Gambler.", into_tech: false, drinks_alcohol: true, multilingual: true)
Suspect.create(name: "Ewelina Szoda", age: 28, gender: "F", location: "London", hair_color: "red", one_thing_about: "Likes energy drink.", into_tech: true, drinks_alcohol: true, multilingual: true)
Suspect.create(name: "Douglas Martin", age: 21, gender: "M", location: "London", hair_color: "brown", one_thing_about: "Got a huge swimming pool", into_tech: true, drinks_alcohol: true, multilingual: true)
Suspect.create(name: "Gbenga Ojo-Aromokudu", age: 30, gender: "M", location: "London", hair_color: "blonde", one_thing_about: "Dogs over cats", into_tech: true, drinks_alcohol: true, multilingual: false)
Suspect.create(name: "Jamie S-Tyler", age: 28, gender: "M", location: "London", hair_color: "blonde", one_thing_about: "Plays Broadland3", into_tech: true, drinks_alcohol: true, multilingual: true)
Suspect.create(name: "Juha Penttila", age: 24, gender: "M", location: "London", hair_color: "blonde", one_thing_about: "Loves to ski.", into_tech: false, drinks_alcohol: true, multilingual: true)
Suspect.create(name: "Julian Wakefild", age: 25, gender: "M", location: "London", hair_color: "black", one_thing_about: "Loves dogs.", into_tech: true, drinks_alcohol: true, multilingual: false)
Suspect.create(name: "Mina Malaj", age: 23, gender: "F", location: "London", hair_color: "black", one_thing_about: "Plays football.", into_tech: true, drinks_alcohol: false, multilingual: true)
Suspect.create(name: "Manuel Jukisz", age: 21, gender: "M", location: "Caracas", hair_color: "brown", one_thing_about: "Loves to run.", into_tech: false, drinks_alcohol: false, multilingual: true)
Suspect.create(name: "Saif Minhas", age: 24, gender: "M", location: "London", hair_color: "blonde", one_thing_about: "Likes to wear hats.", into_tech: true, drinks_alcohol: false, multilingual: true)
Suspect.create(name: "Zakiri Badiru", age: 30, gender: "M", location: "London", hair_color: "black", one_thing_about: "Has an affinity for birds.", into_tech: true, drinks_alcohol: false, multilingual: true)
Suspect.create(name: "Adao Natalino", age: 23, gender: "M", location: "London", hair_color: "brown", one_thing_about: "Likes to sing.", into_tech: true, drinks_alcohol: true, multilingual: true)

CaseSuspect.create(suspect_id: 1, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 2, case_id: 1, guilt: true)
CaseSuspect.create(suspect_id: 3, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 4, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 5, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 6, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 7, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 8, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 9, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 10, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 11, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 12, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 13, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 14, case_id: 1, guilt: false)
CaseSuspect.create(suspect_id: 15, case_id: 1, guilt: false)

Case.create(title: "Flatiron Theft", detective_id: 1)

Detective.create(name: "Adao")